// <auto-generated />
using System;
using ChurchApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChurchApp.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    partial class AplicacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ChurchApp.Modelo", b =>
                {
                    b.Property<int>("IntegranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellidos")
                        .HasColumnType("TEXT");

                    b.Property<int>("Cantidad_Disciplina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad_Hijos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Causas_Disciplina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciudad_Nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciudad_Residencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Congregacion_Anterior")
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Denominacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Disciplina")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado_Civil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Expulsado")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Bautismo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Conversion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Miembro")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hijos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nivel_Estudio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Conyuge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Empresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Iglesia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Pastor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocupaciones")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais_Nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais_Residencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pregunta1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pregunta2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pregunta3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pregunta4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pregunta5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Profesion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Razon_Expulsion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono_Empresa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_Documento")
                        .HasColumnType("TEXT");

                    b.HasKey("IntegranteId");

                    b.ToTable("Integrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
